### ISSUE TITLE
Fatal error: Class 'Dukt\OAuth\Providers\BaseProvider' not found

### ISSUE THREAD

**Issue by afairhurst** [carlcs/craft-instagram#1]
Hi Carlcs,

Thanks for providing this Dukt OAuth plugin here on github.

I've tried to install it, however it causes an error on the OAuth Admin page.

`Fatal error: Class 'Dukt\OAuth\Providers\BaseProvider' not found in /Users/username/Sites/sitename/craft/plugins/instagram/providers/oauth/Instagram.php on line 7`

I'm having the same [issue](https://github.com/dukt/craft-linkedin/issues/1) with Dukt Linkedin.

I've tried reinstalling the plugins multiple times to no avail.

I suspect I'm missing something very obvious, however don't know where to turn.

Many Thanks,

Andrew

**Comment by carlcs** [comment]
Hey there, it looks like the providers need to be updated to latest versions of the OAuth plugin. Please use OAuth 1.0.79 in the meantime.

https://github.com/dukt/craft-oauth/releases

**Comment by afairhurst** [comment]
Hi Carlcs, Fantastic. Thanks for the suggestion; that hadn't occurred to me. Working fine now. Thanks so much! I'll look out for updated versions of the provider plugins.
